# Generated by Django 3.2.15 on 2023-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschoolapp', '0008_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroup',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
